<?php /* Events List Feature */ ?>
<div align = "center" 
style = "width: 300px; 
height: 369px; 
background-color: white; 
border: solid 15px white; 
border-radius: 2px; 
margin-top: 8px; 
padding-top: 1px; 
padding-left: 20px; 
padding-right: 20px; 
box-shadow: 0px 0px 5px 1px #ccc">

<table>
	<tr>
    	<td valign = 'middle' style = ' height: 50px; border-top: solid 1px #E6E6E6; padding-top: 5px; border-bottom: solid 1px #E6E6E6; padding-bottom: 5px'>
        <img src = '/LyfSync/Search.png' valign = 'middle' style = 'height: 24px; margin-right: 5px'>
        <input type='text' name='Search' style='font-family: Calibri; font-size: 13px; width: 265px; height: 27px; background-color: #ffffff; border-radius: 4px; border:solid 1px #BFBDBD; box-shadow: 0px 0px 0 #E6E6E6 inset; padding-left: 6px' placeholder='Search for Events in Your Area'>
        </td>
<?php /* The following are still treated as test elements generated by the browser on the client-side - Information contained in the following elements will have to be replaced by dummy data by the end of February */ ?>
    </tr>
	<tr>
    	<td valign = 'bottom' style = 'height: 100px'>
<?php include "eventthumbnail.php"; ?>
		</td>
    </tr>
	<tr>
    	<td valign = 'bottom' style = 'height: 95px; margin-top: 5px'>
<?php include "eventthumbnail.php"; ?>
		</td>
    </tr>	
	<tr>
    	<td valign = 'bottom' style = 'height: 95px; margin-top: 5px'>
<?php include "eventthumbnail.php"; ?>
		</td>
    </tr>
	<tr>
    	<td align = 'right'>
        <a href = '.php'>
        <font face = 'Calibri' size = '2' color = 'Grey'><u>See All</u></font></a>
        </td>
    </tr>
</table>
</div>